"""empty message

Revision ID: 48912a6560fe
Revises: 3177de7776ab
Create Date: 2026-03-09 23:51:32.914960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48912a6560fe'
down_revision = '3177de7776ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('id_planeta',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_nave',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('id_nave',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_planeta',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
